/////////////////////////////////////////////////////////////////////////////
// Name:        about.h
// Purpose:     
// Author:      
// Modified by: 
// Created:     09/11/2010 16:05:24
// RCS-ID:      
// Copyright:   Visual Collaboration Technologies Inc.
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 09/11/2010 16:05:24

#ifndef _ABOUT_H_
#define _ABOUT_H_


/*!
 * Includes
 */

////@begin includes
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_ABOUT 10008
#define ID_OK_BUTTON 10009
#define SYMBOL_ABOUT_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX|wxTAB_TRAVERSAL
#define SYMBOL_ABOUT_TITLE _("About VMoveCAD 2011 R1 (Beta)")
#define SYMBOL_ABOUT_IDNAME ID_ABOUT
#define SYMBOL_ABOUT_SIZE wxSize(400, 300)
#define SYMBOL_ABOUT_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * About class declaration
 */

class About: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( About )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    About();
    About( wxWindow* parent, wxWindowID id = SYMBOL_ABOUT_IDNAME, const wxString& caption = SYMBOL_ABOUT_TITLE, const wxPoint& pos = SYMBOL_ABOUT_POSITION, const wxSize& size = SYMBOL_ABOUT_SIZE, long style = SYMBOL_ABOUT_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_ABOUT_IDNAME, const wxString& caption = SYMBOL_ABOUT_TITLE, const wxPoint& pos = SYMBOL_ABOUT_POSITION, const wxSize& size = SYMBOL_ABOUT_SIZE, long style = SYMBOL_ABOUT_STYLE );

    /// Destructor
    ~About();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin About event handler declarations

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_OK_BUTTON
    void OnOkButtonClick( wxCommandEvent& event );

////@end About event handler declarations

////@begin About member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end About member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin About member variables
////@end About member variables
};

#endif
    // _ABOUT_H_
