/////////////////////////////////////////////////////////////////////////////
// Name:        vmovecad.h
// Purpose:     
// Author:      
// Modified by: 
// Created:     09/11/2010 14:27:54
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 09/11/2010 14:27:54

#ifndef _VMOVECAD_H_
#define _VMOVECAD_H_


/*!
 * Includes
 */

////@begin includes
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_VMOVECAD 10000
#define ID_TEXTCTRL 10001
#define SYMBOL_VMOVECAD_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX|wxTAB_TRAVERSAL
#define SYMBOL_VMOVECAD_TITLE _("vmovecad")
#define SYMBOL_VMOVECAD_IDNAME ID_VMOVECAD
#define SYMBOL_VMOVECAD_SIZE wxSize(400, 300)
#define SYMBOL_VMOVECAD_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * VMoveCAD class declaration
 */

class VMoveCAD: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( VMoveCAD )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    VMoveCAD();
    VMoveCAD( wxWindow* parent, wxWindowID id = SYMBOL_VMOVECAD_IDNAME, const wxString& caption = SYMBOL_VMOVECAD_TITLE, const wxPoint& pos = SYMBOL_VMOVECAD_POSITION, const wxSize& size = SYMBOL_VMOVECAD_SIZE, long style = SYMBOL_VMOVECAD_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_VMOVECAD_IDNAME, const wxString& caption = SYMBOL_VMOVECAD_TITLE, const wxPoint& pos = SYMBOL_VMOVECAD_POSITION, const wxSize& size = SYMBOL_VMOVECAD_SIZE, long style = SYMBOL_VMOVECAD_STYLE );

    /// Destructor
    ~VMoveCAD();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin VMoveCAD event handler declarations

////@end VMoveCAD event handler declarations

////@begin VMoveCAD member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end VMoveCAD member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin VMoveCAD member variables
////@end VMoveCAD member variables
};

/*!
 * vmovecad class declaration
 */

class vmovecad: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( vmovecad )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    vmovecad();
    vmovecad( wxWindow* parent, wxWindowID id = SYMBOL_VMOVECAD_IDNAME, const wxString& caption = SYMBOL_VMOVECAD_TITLE, const wxPoint& pos = SYMBOL_VMOVECAD_POSITION, const wxSize& size = SYMBOL_VMOVECAD_SIZE, long style = SYMBOL_VMOVECAD_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_VMOVECAD_IDNAME, const wxString& caption = SYMBOL_VMOVECAD_TITLE, const wxPoint& pos = SYMBOL_VMOVECAD_POSITION, const wxSize& size = SYMBOL_VMOVECAD_SIZE, long style = SYMBOL_VMOVECAD_STYLE );

    /// Destructor
    ~vmovecad();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin vmovecad event handler declarations

////@end vmovecad event handler declarations

////@begin vmovecad member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end vmovecad member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin vmovecad member variables
////@end vmovecad member variables
};

#endif
    // _VMOVECAD_H_
