/////////////////////////////////////////////////////////////////////////////
// Name:        vmovecad.cpp
// Purpose:     
// Author:      
// Modified by: 
// Created:     09/11/2010 14:27:54
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 09/11/2010 14:27:54

// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

#ifdef __BORLANDC__
#pragma hdrstop
#endif

#ifndef WX_PRECOMP
#include "wx/wx.h"
#endif

////@begin includes
////@end includes

#include "vmovecad.h"

////@begin XPM images
////@end XPM images


/*
 * VMoveCAD type definition
 */

IMPLEMENT_DYNAMIC_CLASS( VMoveCAD, wxDialog )


/*
 * VMoveCAD event table definition
 */

BEGIN_EVENT_TABLE( VMoveCAD, wxDialog )

////@begin VMoveCAD event table entries
////@end VMoveCAD event table entries

END_EVENT_TABLE()


/*
 * VMoveCAD constructors
 */

VMoveCAD::VMoveCAD()
{
    Init();
}

VMoveCAD::VMoveCAD( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
    Init();
    Create(parent, id, caption, pos, size, style);
}


/*
 * VMoveCAD creator
 */

bool VMoveCAD::Create( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
////@begin VMoveCAD creation
    SetExtraStyle(wxWS_EX_BLOCK_EVENTS);
    wxDialog::Create( parent, id, caption, pos, size, style );

    CreateControls();
    Centre();
////@end VMoveCAD creation
    return true;
}


/*
 * VMoveCAD destructor
 */

VMoveCAD::~VMoveCAD()
{
////@begin VMoveCAD destruction
////@end VMoveCAD destruction
}


/*
 * Member initialisation
 */

void VMoveCAD::Init()
{
////@begin VMoveCAD member initialisation
////@end VMoveCAD member initialisation
}


/*
 * Control creation for VMoveCAD
 */

void VMoveCAD::CreateControls()
{    
////@begin VMoveCAD content construction
    // Generated by DialogBlocks, 09/11/2010 14:40:46 (unregistered)

    VMoveCAD* itemDialog1 = this;

    wxBoxSizer* itemBoxSizer2 = new wxBoxSizer(wxVERTICAL);
    itemDialog1->SetSizer(itemBoxSizer2);

    wxButton* itemButton3 = new wxButton( itemDialog1, ID_BUTTON, _("Button"), wxDefaultPosition, wxDefaultSize, 0 );

    wxTextCtrl* itemTextCtrl4 = new wxTextCtrl( itemDialog1, ID_TEXTCTRL, wxEmptyString, wxDefaultPosition, wxDefaultSize, 0 );

    wxTextCtrl* itemTextCtrl5 = new wxTextCtrl( itemDialog1, ID_TEXTCTRL1, wxEmptyString, wxDefaultPosition, wxDefaultSize, 0 );

    wxStaticText* itemStaticText6 = new wxStaticText( itemDialog1, wxID_STATIC, _("Static text"), wxDefaultPosition, wxDefaultSize, 0 );

////@end VMoveCAD content construction
}


/*
 * Should we show tooltips?
 */

bool VMoveCAD::ShowToolTips()
{
    return true;
}

/*
 * Get bitmap resources
 */

wxBitmap VMoveCAD::GetBitmapResource( const wxString& name )
{
    // Bitmap retrieval
////@begin VMoveCAD bitmap retrieval
    wxUnusedVar(name);
    return wxNullBitmap;
////@end VMoveCAD bitmap retrieval
}

/*
 * Get icon resources
 */

wxIcon VMoveCAD::GetIconResource( const wxString& name )
{
    // Icon retrieval
////@begin VMoveCAD icon retrieval
    wxUnusedVar(name);
    return wxNullIcon;
////@end VMoveCAD icon retrieval
}


/*
 * vmovecad type definition
 */

IMPLEMENT_DYNAMIC_CLASS( vmovecad, wxDialog )


/*
 * vmovecad event table definition
 */

BEGIN_EVENT_TABLE( vmovecad, wxDialog )

////@begin vmovecad event table entries
////@end vmovecad event table entries

END_EVENT_TABLE()


/*
 * vmovecad constructors
 */

vmovecad::vmovecad()
{
    Init();
}

vmovecad::vmovecad( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
    Init();
    Create(parent, id, caption, pos, size, style);
}


/*
 * vmovecad creator
 */

bool vmovecad::Create( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
////@begin vmovecad creation
    SetExtraStyle(wxWS_EX_BLOCK_EVENTS);
    wxDialog::Create( parent, id, caption, pos, size, style );

    CreateControls();
    Centre();
////@end vmovecad creation
    return true;
}


/*
 * vmovecad destructor
 */

vmovecad::~vmovecad()
{
////@begin vmovecad destruction
////@end vmovecad destruction
}


/*
 * Member initialisation
 */

void vmovecad::Init()
{
////@begin vmovecad member initialisation
////@end vmovecad member initialisation
}


/*
 * Control creation for vmovecad
 */

void vmovecad::CreateControls()
{    
////@begin vmovecad content construction
    // Generated by DialogBlocks, 09/11/2010 14:44:43 (unregistered)

    vmovecad* itemDialog1 = this;

    wxBoxSizer* itemBoxSizer2 = new wxBoxSizer(wxVERTICAL);
    itemDialog1->SetSizer(itemBoxSizer2);

    wxStaticText* itemStaticText3 = new wxStaticText( itemDialog1, wxID_STATIC, _("Static text"), wxDefaultPosition, wxDefaultSize, 0 );

    wxTextCtrl* itemTextCtrl4 = new wxTextCtrl( itemDialog1, ID_TEXTCTRL, wxEmptyString, wxDefaultPosition, wxDefaultSize, 0 );

////@end vmovecad content construction
}


/*
 * Should we show tooltips?
 */

bool vmovecad::ShowToolTips()
{
    return true;
}

/*
 * Get bitmap resources
 */

wxBitmap vmovecad::GetBitmapResource( const wxString& name )
{
    // Bitmap retrieval
////@begin vmovecad bitmap retrieval
    wxUnusedVar(name);
    return wxNullBitmap;
////@end vmovecad bitmap retrieval
}

/*
 * Get icon resources
 */

wxIcon vmovecad::GetIconResource( const wxString& name )
{
    // Icon retrieval
////@begin vmovecad icon retrieval
    wxUnusedVar(name);
    return wxNullIcon;
////@end vmovecad icon retrieval
}
