name: Releases
on:
 push:
   paths:
     - .github/workflows/main.yml
jobs:
  build:
    runs-on: windows-latest
    
    env: 
      VMCAD_DEP: D:\a\VMoveCAD\VMoveCAD\dependency\VMoveCAD_DEPS
      VC_BUILD_DIR: D:\a\VMoveCAD\VMoveCAD
      VC_BUILD_DIR1: D:\a\VMoveCAD\VMoveCAD\VMoveCAD_MFC_GUI
      
    steps:
      - uses: actions/checkout@v2.3.4
      
           
      - name: Download the file from url
        uses: suisei-cn/actions-download-file@v1.0.1
        with:
          url: "https://downloads.vcollab.com/VCollab_Build_CI/VMoveCAD/VMoveCAD_DEPS.7z"
          target: dependency
          
      - name: Extract zip file 
        uses: DuckSoft/extract-7z-action@v1.0
        with:
           pathsource: dependency\VMoveCAD_DEPS.7z
           pathtarget: dependency
    
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64

      - name: Install Windows SDK
        uses: ChristopheLav/windows-sdk-install@v1
        with:
          version-sdk: 17763
          features: 'OptionId.DesktopCPPx64,OptionId.DesktopCPPx86,OptionId.DesktopCPParm64'
          
      - name: Build app for release
        run: |
            msbuild VMoveCAD.sln -t:rebuild /p:Platform=x64 /p:Configuration=Release /p:LocalizedBuild=true /p:WindowsTargetPlatformVersion=10.0.17763.0 > cadlog.txt
            msbuild VMoveCAD_MFC_GUI\VMoveCAD_MFC_GUI.vcxproj -t:rebuild /p:Platform=x64 /p:Configuration=Release /p:LocalizedBuild=true /p:WindowsTargetPlatformVersion=10.0.17763.0 > cadlog.txt 
            msbuild VMoveCAD_Batch.vcxproj -t:rebuild /p:Platform=x64 /p:Configuration=Release /p:LocalizedBuild=true /p:WindowsTargetPlatformVersion=10.0.17763.0 > cadlog.txt
           
      -  name: copy a file
         run: |
             copy "D:\a\VMoveCAD\VMoveCAD\VMoveCAD\x64\release\VMoveCADBatch.exe" "D:\a\VMoveCAD\VMoveCAD\vmovecadexe"       
             copy "D:\a\VMoveCAD\VMoveCAD\VMoveCAD\x64\release\VMoveCAD.exe" "D:\a\VMoveCAD\VMoveCAD\vmovecadexe"  
             copy "D:\a\VMoveCAD\VMoveCAD\VMoveCAD\x64\release\CadInfo.exe" "D:\a\VMoveCAD\VMoveCAD\vmovecadexe" 
          
      - name: log files uploaded to ftp.
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
         server: ${{ secrets.FTP_SERVER }}
         username: ${{ secrets.FTP_USERNAME }}
         password: ${{ secrets.FTP_PASSWORD }}
         protocol: ftps
         port : 2133
         local-dir: ./vmovecadexe/       
         server-dir: ./test/  
          
          
      - name: Send email notification on success
        uses: dawidd6/action-send-mail@v3.7.1
        with:
          server_address: smtp.gmail.com
          server_port: 465 
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject:  job status Notification
          Body: |
             VMoveCAD build was success.
             https://downloads.vcollab.com/aravinth/test/VMoveCADBatch.exe
             https://downloads.vcollab.com/aravinth/test/VMoveCAD.exe
             https://downloads.vcollab.com/aravinth/test/CadInfo.exe
             
          To: mounikakallepalli@vcollab.com
          from: Kallepallimounika333@gmail.com
          content_type: text/html
         
      - name: Send email notification on failure.
        if: ${{ failure() }}
        uses: dawidd6/action-send-mail@v3.7.1
        with:
          server_address: smtp.gmail.com
          server_port: 465 
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject:  job status Notification
          Body: |
            VMoveCAD build was failure
          To: mounikakallepalli@vcollab.com
          from: Kallepallimounika333@gmail.com
          content_type: text/html
          attachments: |
             D:\a\VMoveCAD\VMoveCAD\cadlog.txt
             D:\a\VMoveCAD\VMoveCAD\cadlog.txt
             D:\a\VMoveCAD\VMoveCAD\cadlog.txt

      - name: Upload VMoveCAD.exe
        uses: actions/upload-artifact@v2
        with:
          name: VMoveCAD.exe
          path:  D:\a\VMoveCAD\VMoveCAD\VMoveCAD\x64\release\VMoveCAD.exe
          
      - name: Download artifact 
        uses: actions/download-artifact@v3
        with:
          name: VMoveCAD.exe
      - name: archive site content
        uses: thedoctor0/zip-release@master
        with:
           filename: VMoveCAD.exe.zip

         
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v2.0.0
          release_name: VMoveCAD.exe

          body: |
            # Release Notes

            This is the first release of my project.

            ## Features

            - first change
            - second change

          draft: false
          prerelease: false
          
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./ VMoveCAD.exe.zip
          asset_name:  VMoveCAD.exe.zip
          asset_content_type: application/zip    
        
     
      
             
          
