name: VCollabPro_CI
on:
 push:
   paths:
     - .github/workflows/main.yml
    
 workflow_dispatch:
jobs:
 build:
    runs-on: windows-latest
    env:
       VMCAD_DEP: VMCAD_DEP\VMoveCAD_DEPS
        
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Download the file from url
        id: download_file  
        uses: suisei-cn/actions-download-file@v1.0.1
        with:
          url: "https://downloads.vcollab.com/VCollab_Build_CI/VMoveCAD/VMoveCAD_DEPS.7z"
          target: VMCAD_DEP\
          
      - name: Extract zip file
        uses:  DuckSoft/extract-7z-action@v1.0
        with:
            pathsource: VMCAD_DEP\VMoveCAD_DEPS.7z
            pathtarget: VMCAD_DEP
 
      - name: Install Windows SDK
        uses: ChristopheLav/windows-sdk-install@v1
        with:
          version-sdk: 17763
          features: 'OptionId.DesktopCPPx64,OptionId.DesktopCPPx86,OptionId.DesktopCPParm64'
          
      - name: UseDotNet@2
        uses: owner/repo@ref
        with:
              version: '6.x'
              includePreviewVersions: true

      - name: Build Solutions
        run: |
          cd ./VMoveCAD
          msbuild VMoveCAD.sln /p:Configuration=Release
          msbuild VMoveCAD_Batch.sln /p:Configuration=Release
          msbuild CadInfo.sln /p:Configuration=Release
          msbuild VMoveCAD_MFC_GUI\VMoveCAD_MFC_GUI.sln /p:Configuration=Release

          
                
