name: Releases
on:
 push:
   paths:
     - .github/workflows/main.yml
jobs:
  build:
    runs-on: windows-latest
    
    env: 
      VMCAD_DEP: D:\a\VMoveCAD\VMoveCAD\dependency\VMoveCAD_DEPS
      VC_BUILD_DIR: D:\a\VMoveCAD\VMoveCAD
      VC_BUILD_DIR1: D:\a\VMoveCAD\VMoveCAD\VMoveCAD_MFC_GUI
    
    steps:
      - uses: actions/checkout@v2.3.4
      
      - name: Download the file from url
        uses: suisei-cn/actions-download-file@v1.0.1
        with:
          url: "https://downloads.vcollab.com/VCollab_Build_CI/VMoveCAD/VMoveCAD_DEPS.7z"
          target: dependency
          
      - name: Extract zip file 
        uses: DuckSoft/extract-7z-action@v1.0
        with:
           pathsource: dependency\VMoveCAD_DEPS.7z
           pathtarget: dependency
           
     # - name: list of files
      #  run: |
         #cd D:\a\VMoveCAD\VMoveCAD\dependency\VMoveCAD_DEPS
        # ls
       
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64

      - name: Install Windows SDK
        uses: ChristopheLav/windows-sdk-install@v1
        with:
          version-sdk: 17763
          features: 'OptionId.DesktopCPPx64,OptionId.DesktopCPPx86,OptionId.DesktopCPParm64'
          
      - name: Build app for release
        run: |
          msbuild VMoveCAD.sln -t:rebuild /p:Platform=x64 /p:Configuration=Release /p:LocalizedBuild=true /p:WindowsTargetPlatformVersion=10.0.17763.0
          msbuild VMoveCAD_MFC_GUI\VMoveCAD_MFC_GUI.vcxproj -t:rebuild /p:Platform=x64 /p:Configuration=Release /p:LocalizedBuild=true /p:WindowsTargetPlatformVersion=10.0.17763.0
          msbuild VMoveCAD_Batch.vcxproj -t:rebuild /p:Platform=x64 /p:Configuration=Release /p:LocalizedBuild=true /p:WindowsTargetPlatformVersion=10.0.17763.0
          
          
      - name: Push changes
        run: |
            git config --local user.email "kallepallimounika123@yahoo.com"
            git config --local user.name "Mounik05"
            git add .
            git commit -m "Add changes" -a
            git push -u origin master
          
          
       
          

          
          
          
       
          
