name: releases
on:
  push:
    branches: ["master"]

env:
  if: exists('D:\a\VMoveCAD\VMoveCAD\test\New Text Document.txt')
  
jobs:
  check_file:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check if file exists
        id: check_file_changed
        run: |
          if (Test-Path "D:\a\VMoveCAD\VMoveCAD\test\New Text Document.txt") {
            echo "file_exists=true" >> $GITHUB_ENV
          } else {
            echo "file_exists=false" >> $GITHUB_ENV
          }
  build:
    needs: check_file
    runs-on: windows-latest
    env: 
      VMCAD_DEP: D:\a\VMoveCAD\VMoveCAD\dependency\VMoveCAD_DEPS
      VC_BUILD_DIR: D:\a\VMoveCAD\VMoveCAD
      VC_BUILD_DIR1: D:\a\VMoveCAD\VMoveCAD\VMoveCAD_MFC_GUI
    
    steps:
      - uses: actions/checkout@v2.3.4
      
      - name: Download the file from url
        uses: suisei-cn/actions-download-file@v1.0.1
        with:
          url: "https://downloads.vcollab.com/VCollab_Build_CI/VMoveCAD/VMoveCAD_DEPS.7z"
          target: dependency
          
      - name: Extract zip file 
        uses: DuckSoft/extract-7z-action@v1.0
        with:
           pathsource: dependency\VMoveCAD_DEPS.7z
           pathtarget: dependency
           
     # - name: list of files
      #  run: |
         #cd D:\a\VMoveCAD\VMoveCAD\dependency\VMoveCAD_DEPS
        # ls
       
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64

      - name: Install Windows SDK
        uses: ChristopheLav/windows-sdk-install@v1
        with:
          version-sdk: 17763
          features: 'OptionId.DesktopCPPx64,OptionId.DesktopCPPx86,OptionId.DesktopCPParm64'
          
      - name: Build app for release
        run: |
          msbuild VMoveCAD.sln -t:rebuild /p:Platform=x64 /p:Configuration=Release /p:LocalizedBuild=true /p:WindowsTargetPlatformVersion=10.0.17763.0
          msbuild VMoveCAD_MFC_GUI\VMoveCAD_MFC_GUI.vcxproj -t:rebuild /p:Platform=x64 /p:Configuration=Release /p:LocalizedBuild=true /p:WindowsTargetPlatformVersion=10.0.17763.0
          msbuild VMoveCAD_Batch.vcxproj -t:rebuild /p:Platform=x64 /p:Configuration=Release /p:LocalizedBuild=true /p:WindowsTargetPlatformVersion=10.0.17763.0
          
          
      -  name: copy a file
         run: |
             copy "D:\a\VMoveCAD\VMoveCAD\VMoveCAD\x64\release\VMoveCADBatch.exe" "D:\a\VMoveCAD\VMoveCAD\new folder"       
             copy "D:\a\VMoveCAD\VMoveCAD\VMoveCAD\x64\release\VMoveCAD.exe" "D:\a\VMoveCAD\VMoveCAD\new folder"  
             copy "D:\a\VMoveCAD\VMoveCAD\VMoveCAD\x64\release\CadInfo.exe" "D:\a\VMoveCAD\VMoveCAD\new folder"  
          
      - name: upload files to ftp
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
         server: ${{ secrets.FTP_SERVER }}
         username: ${{ secrets.FTP_USERNAME }}
         password: ${{ secrets.FTP_PASSWORD }}
         protocol: ftps
         port : 2133
         local-dir: ./new folder/       
         server-dir: ./test/  
         
      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: VMoveCAD
          path: |
                VMoveCADBatch.exe 
                VMoveCAD.exe
                CadInfo.exe
          
      - name: Upload artifact file
        uses: actions/upload-artifact@v2
        with:
          name: VMoveCAD
          path: |
                D:\a\VMoveCAD\VMoveCAD\VMoveCAD\x64\release\VMoveCADBatch.exe
                D:\a\VMoveCAD\VMoveCAD\VMoveCAD\x64\release\VMoveCAD.exe
                D:\a\VMoveCAD\VMoveCAD\VMoveCAD\x64\release\CadInfo.exe
                
                  
      - name: Create commit message file
        run: |
           git log --pretty=format:"mounikakallepalli@vcollab.com- Mounik05, 26-06-2023 +11:50 : Build automation test: %s" >new.txt
         
      - name: Commit message file
        run: |
           git config --global user.email "mounikakallepalli333@gmail.com"
           git config --global user.name "Mounik05"
           git add .
           git commit -m "add new.txt"
           
           
      - name: Send Email with Attachment and Commit File.
        uses: dawidd6/action-send-mail@v3.7.1
        with:
           server_address: smtp.gmail.com
           server_port: 465 
           username: ${{ secrets.MAIL_USERNAME }}
           password: ${{ secrets.MAIL_PASSWORD }}
           subject: "Email with Attachment "
           Body: "Please find the commit message and  attachment attached below"
           To: mounikakallepalli@vcollab.com
           from: kallepallimounika333@gmail.com
           content_type: text/html/zip
           attachments: |
                D:\a\VMoveCAD\VMoveCAD\new.txt

          
          
          
       
          
