name: VCollabPro_CI
on:
 push:
   branches: [ master ]
    
 workflow_dispatch:
jobs:
 build:
    runs-on: windows-latest
    
    env: 
      VCDEP: ..\depency
      VC_BUILD_DIR: D:\a\VMoveCAD\VMoveCAD

        
    steps:
      - uses: actions/checkout@v2.3.4
      
      - uses: suisei-cn/actions-download-file@v1.0.1
        id: download_file  # Remember to give an ID if you need the output filename
        name: Download the file from url
        with:
          url: "https://downloads.vcollab.com/VCollab_Build_CI/VMoveCAD/VMoveCAD_DEPS.7z"
          target: depency
          
      - name: Extract zip file 
        uses: DuckSoft/extract-7z-action@v1.0
        with:
           pathsource: depency\VMoveCAD_DEPS.7z
           pathtarget: depency
      
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64

      - name: Install Windows SDK
        uses: ChristopheLav/windows-sdk-install@v1
        with:
          version-sdk: 17763
          features: 'OptionId.DesktopCPPx64,OptionId.DesktopCPPx86,OptionId.DesktopCPParm64'
          
      - name: Build VMoveCAD
        run: |
          msbuild CadInfo.vcxproj -t:rebuild /p:Platform=x64 /p:Configuration=Release /p:LocalizedBuild=true /p:WindowsTargetPlatformVersion=10.0.17763.0
         
          
          
          
